### ISSUE TITLE
The specified Gradle distribution does not exist.

### ISSUE THREAD

**Issue by joaovieira-ca** [Apress/pro-spring-6#2]
I started reading the book and just cloned the repo, but when using Gradle, I am getting the following error

> The specified Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-8.3-20230504222113+0000-bin.zip' does not exist.

What solved for me was changing the gradle in the wrapper config ([here](https://github.com/Apress/pro-spring-6/blob/da6fd2fc09bf4b1b11c60d51b1db956d00311c91/gradle/wrapper/gradle-wrapper.properties#L3-L3)) from

`distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-8.3-20230504222113+0000-bin.zip`

to 

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip`

Not sure if this is the best solution, but it worked for me :D 

PS: I also needed to add a file `gradle.properties` to the root folder with something like this

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
```

to give Gradle more memory because I was getting `java.lang.OutOfMemoryError: Java heap space`

**Comment by iuliana** [comment]
Hello @jluiz20, 

Thank you for this. I use a local instance of Gradle managed using SDKMAN and I forgot to update the wrapper.  I now upgraded the wrapper to 8.4 too. 

I've never seen the OOM, can you tell me the machine you are using and the JDK?  ( I am using a Apple M1 computer, with the JDK from Amazon - I noticed that it is better at parallel processing and memory consumption at work :D )

Cheers, 
Iuliana Cosmina

**Comment by joaovieira-ca** [comment]
Hi @iuliana. 

The OOM was not the machine, it was in the `gradle` process. (PS: I have 64GB of RAM). Maybe it was because it was trying to resolve all dependencies at once.

Thank you :D
