### ISSUE TITLE
CustomPropertyEditorRegistrar does absolutely nothing

### ISSUE THREAD

**Issue by amitkriit** [Apress/pro-spring-6#5]
**com.apress.prospring6.four.DiverseValuesContainer** contains an inner static class named **CustomPropertyEditorRegistrar**. It is supposed to install the custom date and string editors. However it does absolutely nothing.

**Comment by iuliana** [comment]
Hello [amitkriit](https://github.com/amitkriit), 

You are right. Might be a leftover from old code that I missed. 
It is now removed.

Cheers!
